name: 'Manifest'
description: 'Manage Pull Requests that modify a west manifest'
inputs:
  github-token:
    description: 'The token to authenticate with'
  verbosity-level:
    required: false
    default: '0'
  manifest-path:
    description: 'The path to the manifest file'
    required: true
  checkout-path:
    description: 'The path to the checked out Pull Request'
    default: 'none'
    required: false
  message:
    description: 'Message to post'
    required: false
    default: 'none'
  where:
    description: 'Where to post the message. Use comment or description'
    required: false
    default: 'comment'
  labels:
    description: |
      Comma-separated list of labels with optional module name filter:
        <label>[:<module-name>[;<module-name>[;...]]]'
      Example:
        labels: 'test-bootloader:bootloader;hal;drivers, foo:bar;baz;drivers'
      This will add the 'test-bootloader' label when the bootloader, hal,
      or drivers module is changed, and add the 'foo' label if the bar, baz,
      or drivers module is changed.
    required: false
    default: 'none'
  dnm-labels:
    description: 'Comma-separated list of labels.'
    required: false
    default: 'none'
  label-prefix:
    description: 'Prefix for project-specific labels.'
    required: false
    default: 'none'

runs:
  using: "composite"
  steps: 
    - id: setup-python
      run: |
        pip3 install setuptools wheel
        pip3 install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - id: run-python
      run: |
           python3 ${{ github.action_path }}/action.py -p "${{ inputs.manifest-path }}" \
           --checkout-path "${{ inputs.checkout-path}}" -m "${{ inputs.message }}" \
           -l "${{ inputs.labels }}" --label-prefix "${{ inputs.label-prefix }}" \
           --dnm-labels "${{ inputs.dnm-labels }}" --where "${{ inputs.where }}" \
           -v "${{ inputs.verbosity-level }}"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
