name: 'Manifest'
description: 'Manage Pull Requests that modify a west manifest'
inputs:
  github-token:
    description: 'The token to authenticate with'
  verbosity-level:
    required: false
    default: '0'
  manifest-path:
    description: 'The relative path to the manifest file'
    required: true
  checkout-path:
    description: 'The path to the checked out PR. Relative or absolute depending on
                  whether the GITHUB_WORKSPACE env var is defined'
    default: 'none'
    required: false
  use-tree-checkout:
    description: 'If true, comparison will be made on Git tree checkouts'
    default: 'false'
    required: false
  west-import-flag:
    description: 'West import flag to use when parsing the checked out manifest. 
                  Choices are all, none, self'
    default: 'all'
    required: false
  check-impostor-commits:
    description: 'If true, a check for impostor commits will be performed'
    default: 'false'
    required: false
  message:
    description: 'Message to post'
    required: false
    default: 'none'
  labels:
    description: |
      Comma-separated list of labels with optional module name filter:
        <label>[:<module-name>[;<module-name>[;...]]]'
      Example:
        labels: 'test-bootloader:bootloader;hal;drivers, foo:bar;baz;drivers'
      This will add the 'test-bootloader' label when the bootloader, hal,
      or drivers module is changed, and add the 'foo' label if the bar, baz,
      or drivers module is changed.
    required: false
    default: 'none'
  dnm-labels:
    description: 'Comma-separated list of labels.'
    required: false
    default: 'none'
  label-prefix:
    description: 'Prefix for project-specific labels.'
    required: false
    default: 'none'

runs:
  using: "composite"
  steps: 
    - id: setup-python
      run: |
        pip3 install setuptools wheel
        pip3 install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - id: run-python
      run: |
           python3 ${{ github.action_path }}/action.py -p "${{ inputs.manifest-path }}" \
           --pr "${{ github.repository }}/${{ github.event.pull_request.number }}" \
           --checkout-path "${{ inputs.checkout-path}}" -m "${{ inputs.message }}" \
           -l "${{ inputs.labels }}" --label-prefix "${{ inputs.label-prefix }}" \
           --dnm-labels "${{ inputs.dnm-labels }}"  -v "${{ inputs.verbosity-level }}" \
           --use-tree-checkout "${{ inputs.use-tree-checkout }}" \
           --west-import-flag "${{ inputs.west-import-flag }}" \
           --check-impostor-commits "${{ inputs.check-impostor-commits }}"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
